// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// KnativeEventingListerExpansion allows custom methods to be added to
// KnativeEventingLister.
type KnativeEventingListerExpansion interface{}

// KnativeEventingNamespaceListerExpansion allows custom methods to be added to
// KnativeEventingNamespaceLister.
type KnativeEventingNamespaceListerExpansion interface{}
